cela/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from cela import views, moderacioViews


urlpatterns = patterns('',

        url(r'^(?P<cela>\d+)/$', views.celaview,name='cela'),
        url(r'^nou/$', login_required(views.celaCreateView.as_view()) ,name='cela_nova'),
        url(r'^nouusuari/$', login_required(moderacioViews.peticioAcces) ,name='acces_cela'),
        url(r'^modcela/(?P<pk>\d+)/$', login_required(views.celaUpdateView.as_view()) ,name='edicio_cela'),
        url(r'^modepost/$', login_required(moderacioViews.moderacioPostView) ,name='mode_post'),
        url(r'^modeusers/$', login_required(moderacioViews.acceptar_usuari) ,name='mode_usuaris'),
        url(r'^convidar/$', login_required(views.cela_convidar ),name='convidar_usu_cela'),
        url(r'^users/$', login_required(moderacioViews.usuaris_cela) ,name='usuaris_cela'),
        url(r'^changecell/(?P<cela>\d+)/url/(?P<url>\w+)/$', views.celachange, name='canviar_cela'),
        url(r'^visual/$', login_required(views.visual) ,name='visual'),
        url(r'^visualPost/$', login_required(views.visualPost),name='visualPost'),
        url(r'^tesauro_jerarquic_json/', views.tesauro_jerarquic_json, name='tesauro_jerarquic_json'),
        url(r'^tesauro_jerarquic/', login_required(views.tesauro_jerarquic), name='tesauro_jerarquic'),
        url(r'^network/', login_required(views.network), name='network'),
        url(r'^visualcelas/', views.VisualCelas, name='VisualCelas'),
        url(r'^missatge_cela/', login_required(moderacioViews.missatge_cela), name='missatge_cela'),
        url(r'^acceptarRebutjarPost/(?P<pkpost>\d+)/(?P<action>\w+)$', login_required(moderacioViews.acceptarRebutjarPost), name='acceptarRebutjarPost'),
        url(r'^', views.ruscView, name="rusc"),
)

rusc/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import RedirectView
admin.autodiscover()
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    #url(r'^accounts/', include('registration.backends.simple.urls')),
    #url para que no pida el confirmar logout
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^accounts/profile/$', TemplateView.as_view(template_name='profile.html')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/usuari/perfil')),

    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^forum/', include('xarxa.post.urls')),
    url(r'^cela/', include('cela.urls')),
    url(r'^rusc/', include('cela.urls')),
    url(r'^usuari/', include('xarxa.usuari.urls')),
    # url(r'^autocomplete/', include('autocomplete_light.urls')),

    url(r'^busk/', include('xarxa.buscador.urls')),
    url(r'^recurs/', include('xarxa.recurs.urls')),
    url(r'^etiqueta/', include('xarxa.etiqueta.urls')),
    url(r'^missatgeModeracio/', include('xarxa.missatgeModeracio.urls')),
    url(r'^messages/', include('django_messages.urls')),
    url('^inbox/notifications/', include('notifications.urls', namespace="notifications")),
    url(r'^faq/', include('xarxa.faq.urls')),
    url(r'^linkMeta/', include('linksMeta.urls')),
    url(r'^resums/', include('xarxa.resums.urls')),
    url(r'^ficha/', include('xarxa.ficha.urls')),


    #url(r'^boot/', include('etiqueta.urls')), usuari/perfil/
    # url(r'^', views.ruscView),

    url(r'^$', RedirectView.as_view(url='/rusc/',permanent=False)),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xarxa/post/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required as auth

from xarxa.post.views import postCreateView, VoteFormView
from xarxa.post import views


urlpatterns = patterns('',
    url(r'^post/nou/$', postCreateView ,name='post_nou'),
    url(r'^post/(?P<pk>\d+)/reply/$', postCreateView ,name='post_respon'),
    url(r'^perfil/(?P<pk>\d+)$', views.postView, name='perfil'),
    url(r'^post/(?P<pkpost>\d+)$', views.postView, name='post'),
    url(r'^$', views.forum, name='forum'),
    url(r'^vote/$', auth(VoteFormView.as_view()), name="vote"),

)

xarxa/post/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from xarxa.recurs.models import Recurs
from xarxa.etiqueta.models import Etiqueta
from cela.models import Cela







#classe que gestiona(manager) els vots dels diferents posts. camp 'with_votes' del post
from django.db.models import Count
from django.utils.timezone import now
from django.contrib.contenttypes import generic
from xarxa.missatgeModeracio.models import ModComment
#from cela.moderaciomodels import ModeracioMissatge

class PostVoteCountManager(models.Manager):

    def get_queryset(self):
        return super(PostVoteCountManager, self).get_queryset().annotate(votes=Count('vote'))

class Post(models.Model):

    ESTAT_MODERACIO = (
        ('A','Aprobat'),
        ('R','Rebutjat'),
        ('E','En Tramit'),
    )

    moderacio= models.CharField(max_length=1,choices=ESTAT_MODERACIO, default='E')
    titol = models.CharField(max_length=40)
    text = models.TextField()
    pare = models.ForeignKey('self', related_name='children', blank=True, null=True)
    datahora =models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User)
    recursos = models.ManyToManyField(Recurs, blank=True)
    etiquetes = models.ManyToManyField(Etiqueta, blank=True)
    cela = models.ForeignKey(Cela, related_name='posts', blank=True)
    rank_score = models.FloatField(default=0.0)
    num_comments = models.IntegerField(default=0)

    with_votes =PostVoteCountManager()
    objects = models.Manager()

    missModeracio = generic.GenericRelation(ModComment)

    def __str__(self):
        return self.titol

    #retorna el usuari del ultim missatge de moderació
    def mmoderacio_mis_last(self):
        missatge =self.missModeracio.last()
        return missatge.author

    def get_absolute_url(self):
        return reverse('post', args=[str(self.get_root())] )

    #función que dibuja todos los nodos en forma de arbol
    def as_tree(self):
        children = list(self.children.all())
        branch = bool(children)
        #http://stackoverflow.com/questions/231767/what-does-the-yield-keyword-do-in-python
        yield branch, self
        for child in children:
            for next in child.as_tree():
                yield next
        yield branch, None

    #Busquem el inici del arbre per a mostrar la conversa útil per a respondre
    #ToDo Millorar aquest algoritme per que mostri només un resultat significant no infinit (per exemple, mentre el titol continui sent igual)
    #torna la primary key
    def get_root(self):
        if self.pare == None:
            return self.pk
        else:
            comment_root = self.pare
            while comment_root.pare != None:
                comment_root = comment_root.pare
            return comment_root.pk
    #torna el objecte pare
    def get_root_object(self):
        if self.pare == None:
            return self
        else:
            comment_root = self.pare
            while comment_root.pare != None:
                comment_root = comment_root.pare
            return comment_root


    #Llistat de usuaris subscrits al root de un post
    def get_subscriptors(self):
        post = self.get_root_object()
        users = User.objects.filter(userprofile__subscripcions = post)
        users_cela = User.objects.filter(userprofile__tipusSubscripcio = 'T', userprofile__cela = self.cela)
        user_subscrits = []
        for user in users:
            user_subscrits.append(user)
        for user in users_cela:
            user_subscrits.append(user)
        return user_subscrits

    def set_rank(self):
        #Based on HN ranking algo at http://amix.dk/blog/post/19574
        SECS_IN_HOUR = float(60*60)
        GRAVITY = 1.2

        delta = now() - self.datahora
        item_hour_age = delta.total_seconds() // SECS_IN_HOUR
        votes = self.votes - 1
        self.rank_score = votes / pow((item_hour_age+2), GRAVITY)
        self.save()

    #retorna els participants del fil de conversa
    def participants(self):
        particip = []
        post = self.pare
        Post.objects.filter()

        children = list(post.children.all())
        branch = bool(children)
        yield branch, self
        for child in children:
            for next in child.as_tree():
                particip.append(child.autor)
                yield next
        particip.append(child.autor)
        yield branch
        return particip


def post_post_save(sender, instance, created, *args, **kwargs):
    """Argument explanation:

       sender - The model class. (MyModel)
       instance - The actual instance being saved.
       created - Boolean; True if a new record was created.

       *args, **kwargs - Capture the unneeded `raw` and `using`(1.3) arguments.
    """
    if created==True: #aixo indica que l'objecte es nou, pq no ens interessa que passi per aqui despres de cada .save
       #informem el camp numero de comentaris que penjen del post. cada vegada que es crea un post es suma 1 a tots els pares
        paidre = instance
        while paidre != None:
            paidre = paidre.pare
            if paidre:
                paidre.num_comments = paidre.num_comments + 1
                paidre.save()


from django.db.models.signals import post_save
post_save.connect(post_post_save, sender=Post)




def folksonomia(posts):
    """
        Folksonomia etiquetes_relacionades
        Rep un llistat de posts
        retorna un dicionari amb el nom de la etiqueta i el numero de coincidencies
    """
    d = dict()
    for post_rel in posts:
        for etq in post_rel.etiquetes.all():
            if etq.nom in d:
                #suma els values
                val = d[etq.nom]
                val = val + 1
                d[etq.nom] = val
            else:
                d[etq.nom]= 1
    return d


# from django.db.models.signals import post_save
# def post_handler(sender, instance, created, **kwargs):
# post_save.connect(post_handler, sender=Post)


class Vote(models.Model):
    voter = models.ForeignKey(User)
    post = models.ForeignKey(Post)

    def __str__(self):
        return "%s voted %s" % (self.voter.username, self.post.titol)

xarxa/post/forms.py
# -*- coding: utf-8 -*-
from django import forms

from xarxa.post.models import Post,Vote
from cela.models import get_cela
from xarxa.etiqueta.models import Etiqueta


class postForm(forms.ModelForm):

    etiquetes = forms.ModelChoiceField(queryset="", initial="")

    class Meta:
        model = Post
        exclude = {"autor", "pare", "recursos", "moderacio", "cela", "rank_score", "num_comments"}
        widgets = {}


    def clean(self):
        super(postForm, self).clean() #if necessary
        if 'etiquetes' in self._errors:
            del self._errors['etiquetes']

    def __init__(self, *args,**kwargs):
        try:
            self.request = kwargs.pop('request')
        except:
            pass
        super (postForm,self ).__init__(*args,**kwargs)
        self.fields['titol'].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget.attrs['class'] = 'form-control id_text'
        self.fields['etiquetes'].widget.attrs['class'] = 'form-control'
        self.fields['etiquetes'].widget.attrs['class'] = 'etiquetes'
        self.fields['etiquetes'].widget.attrs['style'] = 'width: 100%'
        self.fields['etiquetes'].widget.attrs['multiple'] = 'multiple'
        try:
            self.fields['etiquetes'].queryset = Etiqueta.objects.filter(cela= get_cela(self.request))
        except:
            self.fields['etiquetes'].queryset = Etiqueta.objects.all()

class VoteForm(forms.ModelForm):

    class Meta:
        model = Vote
        fields = '__all__'

xarxa/post/templates/forum.html
{% extends "base.html" %}
{% load staticfiles %}
{% csrf_token %}
{% block headers %}
    <script src="{% static 'js/vote.js' %}"></script>

    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet" />
    <script src="{% static 'js/select2.js' %}"></script>
    <script>
    //Comento per que no se que fa.
{#        $( document ).ready(function() {#}
{##}
{#            $(".etiquetes").select2({tags: true});#}
{##}
{#        });#}
    </script>

{% endblock %}
{% block content %}

    <a class="btn btn-primary btn-lg" href="{% url 'post_nou'  %}">Nou post</a>
    <br />

    {% include "llistatPost.html" %}

{% endblock %}

xarxa/post/templates/llistatPost.html
        <div class="table-responsive">
        <table class="table table-striped">
{#        <thead>#}
{#                <tr>#}
{#                    <th>Vots</th>#}
{#                    <th>Post</th>#}
{#                    <th>Quan?Qui?</th>#}
{#                    <th>Text</th>#}
{#                    <th>Etiquetes</th>#}
{#                </tr>#}
{#            </thead>#}
        {% for post in posts %}
        <tr>
            <td>
                    <form method="post" action="{% url 'vote' %}" class="vote_form">

                         [{{ post.votes }}]

                        {% csrf_token %}
                         <input type="hidden" id="id_post" name="post" class="hidden_id" value="{{ post.pk }}" />
                         <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
                         {% if not user.is_authenticated %}
                            <button disabled title="Identificat per votar">+</button>
                         {% elif post.pk not in voted %}
                            <button class="btn-primary btn-sm">+</button>
                         {% else %}
                            <button class="btn-primary btn-sm">- </button>
                         {% endif %}
                    </form>

            </td>
            <td>
                <a href="{% url 'post' post.pk  %}"> ({{ post.pk }}) </a>
                <b><a href="{% url 'post' post.pk  %}"> {{ post.titol }}</a></b>
            </td>
            <td>
                <a href="{% url 'post' post.pk  %}">
                <span id="notification_count">{{ post.num_comments }}</span>
                    <span class='glyphicon glyphicon-comment'></span>
                    </a>&nbsp;&nbsp;
                <a class="button" href="{% url 'post_respon' post.pk  %}">
                        Comentar</a>
            </td>

            <td>
                (rank: {{ post.rank_score|slice:":2" }})
            </td>
            <td>
                <div id="div_post_info" class="pull-right">
                     Escrit el:{{ post.datahora }}
                    per:
                    <a href="{% url 'perfil_user' post.autor.pk %}"> {{ post.autor }}</a>)
                </div>
            </td>
            <td>
                {{ post.text|slice:":60" }}
            </td>
            <td>

                {% for etiqueta in post.etiquetes.all %}

                    <a href="{% url 'etiqueta' etiqueta.pk  %}" class="btn  btn-default">
                        <span class='glyphicon glyphicon-tag'>
                             {{ etiqueta.nom}}
                        </span>
                    </a>

                {% endfor %}
            </td>
{#            <td>#}
{#                <form enctype="multipart/form-data" method="post" action="">#}
{#                    {% csrf_token %}#}
{##}
{#                    <input type="hidden" id="id_post" name="post" class="hidden_id" value="{{ post.pk }}" />#}
{#                    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />#}
{#                    {% if not user.is_authenticated %}#}
{#                            <button disabled title="Identificat per etiquetar">+</button>#}
{#                         {% else %}#}
{#                            <button type="submit" value=""><span class="glyphicon glyphicon-plus-sign"></span> </button>#}
{#                         {% endif %}#}
{#                    {{ formEtqs.as_p }}#}
{#                </form>#}
{##}
{##}
{#            </td>#}
        </tr>
        {% endfor %}
        </table>
        </div>

xarxa/post/templates/post.html
{% extends "base.html" %}
{%  load staticfiles %}
{% block headers %}
    <script src="{% static 'js/vote.js' %}"></script>
{% endblock %}
{% block content %}
    <ul>
        {% for branch, obj in root.as_tree %}
            {% if obj %}
                {% if post.pk == obj.pk %}
                     <div class="div_coment div_post">
                {% else %}
                      <div class="div_coment" >
                {% endif  %}
                     {% include "post_extended.html" %}
                </div>
                {% if branch %}
                     {% if post.pk == obj.pk %}
                     <div class="div_coment div_post">
                {% else %}
                      <div class="div_coment" >
                {% endif  %}
            {% endif %}

            {% else %}
                {% if branch %}
                     </div >
                {% endif %}
            {% endif %}
        {% endfor %}
    </ul>



{% endblock %}

xarxa/post/templates/post_extended.html
{% load micawber_tags %}

<form method="post" action="{% url 'vote' %}" class="vote_form">{% csrf_token %}
<div id="div_post_wraper">
        <div id="div_post_vote">
            {% if not user.is_authenticated %}
                <button disabled title="Please login to vote">+</button>
             {% elif obj.pk not in voted %}
                <button>+</button>
             {% else %}
                <button>-</button>
             {% endif %}
             [{{ obj.votes }}]
        </div>
        <div id="div_post_content_wraper">
            <div id="div_post_header">
                <div id="div_post_titol">
                    <a href="{% url 'post'  obj.pk   %}">({{ obj.pk }})</a>
                    <b>{{ obj.titol }}</b>
                    {% if obj.pare_id %}
                        pare:
                       <a href="{% url 'post'  obj.pare_id  %}">{{ obj.pare_id }}</a>
                    {% endif %}

                </div>
                <div id="div_post_info" class="pull-right">
                     Escrit el:{{ obj.datahora }}
                    per:
                    <a href="{% url 'perfil_user' obj.autor.pk %}"> {{ obj.autor }}</a>
                     {{ obj.num_comments }} comentaris )
                </div>
            </div>
            <div id="div_post_content">
                <div id="div_post_text">
                        {{ obj.text|oembed  }}
                </div>


                <div id="div_post_etiquetes" class="text-right">
                    {% for etiqueta in obj.etiquetes.all %}
                        <a href="{% url 'etiqueta' etiqueta.pk  %}" class="btn  btn-default btn-xs">
                        <span class='glyphicon glyphicon-tag'>
                             {{ etiqueta.nom}}
                        </span>
                        </a>
                    {% endfor %}
                </div>
                <div id="div_post_recursos">
                    {% for recurs in obj.recursos.all %}

                        <a href="{% url 'recurs' recurs.pk %}" class="btn  btn-default  btn-xs">
                            <span class='glyphicon glyphicon-folder-open'>
                             <a href="{{ recurs.url}}"> {{ recurs.url}} </a>
                        </span>
                        </a>

                        <br />
                    {% endfor %}
                </div>
                <div id="div_post_respondre">
                    <a href="{% url 'post_respon' obj.pk  %}" class="btn btn-primary btn-sm">Respondre</a>
                </div>
            </div>
        </div>
        <input type="hidden" id="id_post" name="post" class="hidden_id" value="{{ obj.pk }}" />
        <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
</div>
</form>